import { PERMISSIONS } from './permissions.constants.js';

export const ROLE_CODES = Object.freeze({
  SYSADMIN: 'SYSADMIN',
  CLUBHEAD: 'CLUBHEAD',
  FLIGHTMANAGER: 'FLIGHTMANAGER',
  PILOT: 'PILOT',
});

export const ROLE_PERMISSIONS = Object.freeze({
  [ROLE_CODES.CLUBHEAD]: Object.freeze([
    PERMISSIONS.USERS_READ_ALL,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_UPDATE,
    PERMISSIONS.USERS_BLOCK,
    PERMISSIONS.ROLES_ASSIGN,
    PERMISSIONS.PILOTS_READ_PUBLIC,
    PERMISSIONS.PILOTS_READ_ALL,
    PERMISSIONS.PILOT_PROFILES_READ_OWN,
    PERMISSIONS.PILOT_PROFILES_UPDATE_OWN,
    PERMISSIONS.PILOT_PROFILES_READ_ALL,
    PERMISSIONS.PILOT_PROFILES_UPDATE_ALL,
    PERMISSIONS.AUTH_CHANGE_OWN_PASSWORD,
    PERMISSIONS.AUTH_RESET_USER_PASSWORD,
    PERMISSIONS.AUTH_LOGOUT_ALL_SESSIONS,
  ]),
  [ROLE_CODES.FLIGHTMANAGER]: Object.freeze([
    PERMISSIONS.PILOTS_READ_PUBLIC,
    PERMISSIONS.PILOTS_READ_ALL,
    PERMISSIONS.PILOT_PROFILES_READ_OWN,
    PERMISSIONS.PILOT_PROFILES_UPDATE_OWN,
    PERMISSIONS.PILOT_PROFILES_READ_ALL,
    PERMISSIONS.PILOT_PROFILES_UPDATE_ALL,
    PERMISSIONS.AUTH_CHANGE_OWN_PASSWORD,
  ]),
  [ROLE_CODES.PILOT]: Object.freeze([
    PERMISSIONS.PILOTS_READ_PUBLIC,
    PERMISSIONS.PILOT_PROFILES_READ_OWN,
    PERMISSIONS.PILOT_PROFILES_UPDATE_OWN,
    PERMISSIONS.AUTH_CHANGE_OWN_PASSWORD,
  ]),
});
